print("Первый овощ")
first = input()
print("Второй овощ")
second = input()
print("Третий овощ")
third = input()
V1 = first.lower() # lower - ввод слов в нижнем регистре
V2 = second.lower()
V3 = third.lower()
print(V1, V2, V3)
V1 = first.upper() # upper - ввод слов в верхнем регистре
V2 = second.upper()
V3 = third.upper()
print(V1, V2, V3)
V1 = first.capitalize() # capitalize - выводит первую бувку в верхнем регистре
V2 = second.capitalize()
V3 = third.capitalize()
print(V1, V2, V3)
print("Количество", V1, "=")
first_num = int(input())
print("Количество", V2, "=")
second_num = int(input())
print("Количество", V3, "=")
third_num = int(input())
print("Всего: {0} - {1}; {2} - {3}; {4} - {5}.".format(V1, first_num, V2, second_num, V3, third_num))
